# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.realestate.com:
  peer0.builder1.realestate.com:
  peer1.builder1.realestate.com:
  peer0.agent1.realestate.com:
  peer1.agent1.realestate.com:
  peer0.regulator.realestate.com:
  peer1.regulator.realestate.com:

networks:
  default:
    external:
      name: bc-net

services:

  orderer.realestate.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.realestate.com
    container_name: orderer.realestate.com
#    networks:
#      - bc-net

  peer0.builder1.realestate.com:
    container_name: peer0.builder1.realestate.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.builder1.realestate.com
#    networks:
#      - bc-net

  peer1.builder1.realestate.com:
    container_name: peer1.builder1.realestate.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.builder1.realestate.com
#    networks:
#      - bc-net

  peer0.agent1.realestate.com:
    container_name: peer0.agent1.realestate.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.agent1.realestate.com
#    networks:
#      - bc-net

  peer1.agent1.realestate.com:
    container_name: peer1.agent1.realestate.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.agent1.realestate.com
#    networks:
#      - bc-net

#  peer0.regulator.realestate.com:
#    container_name: peer0.regulator.realestate.com
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer0.regulator.realestate.com
#    networks:
#      - bc-net

#  peer1.regulator.realestate.com:
#    container_name: peer1.regulator.realestate.com
#    extends:
#      file:  base/docker-compose-base.yaml
#      service: peer1.regulator.realestate.com
#    networks:
#      - bc-net

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.builder1.realestate.com:7051
      - CORE_PEER_LOCALMSPID=Builder1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/builder1.realestate.com/peers/peer0.builder1.realestate.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/builder1.realestate.com/peers/peer0.builder1.realestate.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/builder1.realestate.com/peers/peer0.builder1.realestate.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/builder1.realestate.com/users/Admin@builder1.realestate.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        #- ~/bc-realestate-app/chaincode:/opt/gopath/src/github.com/chaincode
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.realestate.com
      - peer0.builder1.realestate.com
      - peer1.builder1.realestate.com
      - peer0.agent1.realestate.com
      - peer1.agent1.realestate.com
#      - peer0.regulator.realestate.com
#      - peer1.regulator.realestate.com
#    networks:
#      - bc-net
