# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.realestate.com:
    container_name: orderer.realestate.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/realestate.com/orderers/orderer.realestate.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/realestate.com/orderers/orderer.realestate.com/tls/:/var/hyperledger/orderer/tls
    - orderer.realestate.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.purvankara.realestate.com:
    container_name: peer0.purvankara.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.purvankara.realestate.com
      - CORE_PEER_ADDRESS=peer0.purvankara.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.purvankara.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.purvankara.realestate.com:7051
      - CORE_PEER_LOCALMSPID=PurvankaraMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/purvankara.realestate.com/peers/peer0.purvankara.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/purvankara.realestate.com/peers/peer0.purvankara.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer0.purvankara.realestate.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.purvankara.realestate.com:
    container_name: peer1.purvankara.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.purvankara.realestate.com
      - CORE_PEER_ADDRESS=peer1.purvankara.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.purvankara.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.purvankara.realestate.com:7051
      - CORE_PEER_LOCALMSPID=PurvankaraMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/purvankara.realestate.com/peers/peer1.purvankara.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/purvankara.realestate.com/peers/peer1.purvankara.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer1.purvankara.realestate.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.commonfloor.realestate.com:
    container_name: peer0.commonfloor.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.commonfloor.realestate.com
      - CORE_PEER_ADDRESS=peer0.commonfloor.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.commonfloor.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.commonfloor.realestate.com:7051
      - CORE_PEER_LOCALMSPID=CommonFloorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/commonfloor.realestate.com/peers/peer0.commonfloor.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/commonfloor.realestate.com/peers/peer0.commonfloor.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer0.commonfloor.realestate.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.commonfloor.realestate.com:
    container_name: peer1.commonfloor.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.commonfloor.realestate.com
      - CORE_PEER_ADDRESS=peer1.commonfloor.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.commonfloor.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.commonfloor.realestate.com:7051
      - CORE_PEER_LOCALMSPID=CommonFloorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/commonfloor.realestate.com/peers/peer1.commonfloor.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/commonfloor.realestate.com/peers/peer1.commonfloor.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer1.commonfloor.realestate.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.regulator.realestate.com:
    container_name: peer0.regulator.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regulator.realestate.com
      - CORE_PEER_ADDRESS=peer0.regulator.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.regulator.realestate.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulator.realestate.com/peers/peer0.regulator.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulator.realestate.com/peers/peer0.regulator.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer0.regulator.realestate.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.regulator.realestate.com:
    container_name: peer1.regulator.realestate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.regulator.realestate.com
      - CORE_PEER_ADDRESS=peer1.regulator.realestate.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.regulator.realestate.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.realestate.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulator.realestate.com/peers/peer1.regulator.realestate.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulator.realestate.com/peers/peer1.regulator.realestate.com/tls:/etc/hyperledger/fabric/tls
        - peer1.regulator.realestate.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
